apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: "192.168.0.8"
port: 20250
serializeImagePulls: false
evictionHard:
    memory.available:  "100Mi"
    nodefs.available:  "10%"
    nodefs.inodesFree: "5%"
    imagefs.available: "15%"
    imagefs.inodesFree: "5%"
containerRuntimeEndpoint: unix:///var/run/gontainers.sock
registerNode: false
authentication:
  anonymous:
    enabled: true
  webhook:
    enabled: false
authorization:
  mode: "AlwaysAllow"
